### ISSUE TITLE
【路由和侧边栏】问题

### ISSUE THREAD

**Issue by cenjinhe** [Undertone0809/vuemulate3#1]
当一个路由下面的 children声明的路由只有一个时，请问如何让根路由的title和children路由title都显示？
配置alwaysShow: true属性无效

**Comment by cenjinhe** [comment]
![image](https://github.com/Undertone0809/vuemulate3/assets/103117343/c160982a-8677-4f61-be86-4c030063a1d4)
请问，如果想要上面图中的工作台和首页都显示，怎么办？

**Comment by Hizeros** [comment]
Are there somebody solve this issue?If not ,I wanna try.

**Comment by cenjinhe** [comment]
So far, no one has solved this issue.
If you have a good solution, please email me.
Thank you for your help. 



| |
cenjinhe
|
|
***@***.***
|
在2023年7月16日 ***@***.***> 写道：

Are there somebody solve this issue?If not ,I wanna try.

**Comment by Hizeros** [comment]
你是想要在侧边栏创建两个导航，一个工作台，一个首页吗？

**Comment by cenjinhe** [comment]
是的，工作台是一级菜单，首页是二级菜单（二级菜单目前只有这一个）


| |
cenjinhe
|
|
***@***.***
|
在2023年7月16日 ***@***.***> 写道：

你是想要在侧边栏创建两个导航，一个工作台，一个首页吗？

**Comment by cenjinhe** [comment]
路由配置项：alwaysShow:true好像不起作用，想要这个配置功能
| |
cenjinhe
|
|
***@***.***
|
在2023年7月16日 ***@***.***> 写道：
是的，工作台是一级菜单，首页是二级菜单（二级菜单目前只有这一个）


| |
cenjinhe
|
|
***@***.***
|
在2023年7月16日 ***@***.***> 写道：

你是想要在侧边栏创建两个导航，一个工作台，一个首页吗？

**Comment by Hizeros** [comment]
![adcabb818c50d591d62a85ca444fbb5](https://github.com/Undertone0809/vuemulate3/assets/128156700/f01d564b-8044-4630-b743-5595ca7afb0d)
当你一个路由下面的 children 声明的路由大于1个时，自动会变成嵌套的模式--如组件页面；只有一个时，会将那个子路由当做根路由显示在侧边栏--如引导页面，而alwaysShow:true功能好像是忽略之前定义的规则，一直显示根路由。如果想要实现嵌套菜单，可以尝试使用 Element UI 的导航菜单组件中sub-menu 组件来生成二级菜单

**Comment by cenjinhe** [comment]
（预想效果）
---侧边栏---
1.工作台
       1.1首页    _**问题点： 这里children只 声明了一个路由（首页） ，想把这个首页也显示在 侧边栏中**_
2.测试页面
        2.1 one页面
        2.2 two页面

（实际效果）
---侧边栏---
1.工作台
2.测试页面
        2.1 one页面
        2.2 two页面

>如果想要到达预想效果那样的侧边栏，该如何配置？？？

**Comment by cenjinhe** [comment]
（预想效果）
---侧边栏---
1.工作台
      1.1首页    // 这里children只 声明了一个路由（首页） ，想把这个首页也显示在 侧边栏中
2.测试页面
       2.1 one页面
       2.2 two页面

（实际效果）
---侧边栏---
1.工作台
2.测试页面
       2.1 one页面
       2.2 two页面

>如果想要到达预想效果那样的侧边栏，该如何配置？？？

**Comment by Hizeros** [comment]
![image](https://github.com/Undertone0809/vuemulate3/assets/128156700/05058e5f-4ec6-4467-bea0-42b0738803d7)
你尝试把在这段代码注释一下，应该就没有问题了

**Comment by Undertone0809** [comment]
@cenjinhe  #2 这个pr已经解决了这个问题，你现在可以通过设置alwaysShow的方式来实现这个功能。

**Comment by cenjinhe** [comment]
能这么快的解决这个issue，非常感谢您！


| |
cenjinhe
|
|
***@***.***
|
在2023年7月16日 ***@***.***> 写道：

@cenjinhe#2 这个pr已经解决了这个问题，你现在可以通过设置alwaysShow的方式来实现这个功能。
